# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - unused_closure_parameter
  - line_length
  - return_value_from_void_function
  - type_name
  - force_cast
 
 
